// Generated by Wrangler on Fri Aug 16 2024 14:57:13 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	BROWSER_KV: KVNamespace;
	RENDER_RATE_LIMITER: any;
	AI_AGENT: Ai;
	BACKEND_SECURITY_TOKEN: string
}
