#:schema node_modules/wrangler/config-schema.json
name = "mark-minion"
main = "src/index.ts"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]


[[kv_namespaces]]
binding = "BROWSER_KV"
id = "1cd15d8f3365441ebce086c32617f988"
preview_id = "5dc7e6e71d624f9bba4842801f7dfc8b"

[[unsafe.bindings]]
name = "RENDER_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 5, period = 60 }

[ai]
binding = "AI_AGENT"
